server:
  port: 31001
spring:
  application:
    name: sc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  freemarker:
    cache: false
    settings:
     template_update_delay: 0